version: '3'
services:
  bookwormscommunity:
    image: novacean/bookwormscommunity:latest
    ports:
      - 9090:9090
    depends_on:
      - bookdbcontainer
    networks:
      appnetwork:
        aliases:
            - bookwormscommunity
  bookdbcontainer:
    image: novacean/postgres:latest
    networks:
      appnetwork:
        aliases:
             - bookdbcontainer
    environment:
      - POSTGRES_DB=bookcommunity
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
networks:
  appnetwork:
